package com.men.common.model;

import com.men.common.model.base.BaseTranslate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Translate extends BaseTranslate<Translate> {
	
}

