package com.men.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	public void setIsAdmin(java.lang.Integer isAdmin) {
		set("isAdmin", isAdmin);
	}
	
	public java.lang.Integer getIsAdmin() {
		return getInt("isAdmin");
	}
	
	public void setChecked(java.lang.Integer checked) {
		set("checked", checked);
	}
	
	public java.lang.Integer getChecked() {
		return getInt("checked");
	}
	
	public void setTUsed(java.lang.Integer tUsed) {
		set("tUsed", tUsed);
	}
	
	public java.lang.Integer getTUsed() {
		return getInt("tUsed");
	}
	
	public void setTLast(java.lang.Integer tLast) {
		set("tLast", tLast);
	}
	
	public java.lang.Integer getTLast() {
		return getInt("tLast");
	}
	
	public void setPUsed(java.lang.Integer pUsed) {
		set("pUsed", pUsed);
	}
	
	public java.lang.Integer getPUsed() {
		return getInt("pUsed");
	}
	
	public void setPLast(java.lang.Integer pLast) {
		set("pLast", pLast);
	}
	
	public java.lang.Integer getPLast() {
		return getInt("pLast");
	}
	
}

