package com.men.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePicture<M extends BasePicture<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setTime(java.lang.String time) {
		set("time", time);
	}
	
	public java.lang.String getTime() {
		return getStr("time");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setSrc1(java.lang.String src1) {
		set("src1", src1);
	}
	
	public java.lang.String getSrc1() {
		return getStr("src1");
	}
	
	public void setSrc2(java.lang.String src2) {
		set("src2", src2);
	}
	
	public java.lang.String getSrc2() {
		return getStr("src2");
	}
	
}

