package com.men.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTranslate<M extends BaseTranslate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setTime(java.lang.String time) {
		set("time", time);
	}
	
	public java.lang.String getTime() {
		return getStr("time");
	}
	
	public void setFrom1(java.lang.String from1) {
		set("from1", from1);
	}
	
	public java.lang.String getFrom1() {
		return getStr("from1");
	}
	
	public void setTo1(java.lang.String to1) {
		set("to1", to1);
	}
	
	public java.lang.String getTo1() {
		return getStr("to1");
	}
	
	public void setQ(java.lang.String q) {
		set("q", q);
	}
	
	public java.lang.String getQ() {
		return getStr("q");
	}
	
	public void setResult(java.lang.String result) {
		set("result", result);
	}
	
	public java.lang.String getResult() {
		return getStr("result");
	}
	
}

